apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: cloudflare
stringData:
  token: <YOUR_TUNNEL_TOKEN>
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
  labels:
    name: development